FROM python:3.9-slim-buster

WORKDIR /cool_counters

# Install required packages
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy the rest of the code
COPY . .

EXPOSE 8001

CMD ["python3", "manage.py", "runserver", "0.0.0.0:8001"]
